/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author vboxuser
 */
public class frmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtApellido = new javax.swing.JTextField();
        jtxtNombre1 = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtContrasena = new javax.swing.JPasswordField();
        jcbxTipoUsuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro - Iron Fit");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtApellido.setBackground(new java.awt.Color(0,0,0,1));
        jtxtApellido.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jtxtApellido.setForeground(new java.awt.Color(255, 255, 255));
        jtxtApellido.setBorder(null);
        getContentPane().add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 340, 30));

        jtxtNombre1.setBackground(new java.awt.Color(0,0,0,1));
        jtxtNombre1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jtxtNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jtxtNombre1.setBorder(null);
        getContentPane().add(jtxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 340, 30));

        jtxtEmail.setBackground(new java.awt.Color(0,0,0,1));
        jtxtEmail.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEmail.setBorder(null);
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 423, 340, 30));

        jtxtContrasena.setBackground(new java.awt.Color(0,0,0,1));
        jtxtContrasena.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jtxtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jtxtContrasena.setBorder(null);
        getContentPane().add(jtxtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 542, 340, 30));

        jcbxTipoUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jcbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        getContentPane().add(jcbxTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 482, 190, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 240, 30));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registro.png"))); // NOI18N
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jcbxTipoUsuario;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JPasswordField jtxtContrasena;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre1;
    // End of variables declaration//GEN-END:variables
}
